# netlify.toml

[build]
  # This is the command Netlify will run to build your site.
  command = "npm run build"

  # This is the folder Netlify will deploy.
  publish = "dist"

  # This is the directory Netlify will run the build command in.
  # This is the setting that fixes your issue.
  base = "apparent-asteroid"